---
AWSTemplateFormatVersion: '2010-09-09'
Description: IAM role for serviceaccount "kube-system/alb-ingress-controller" [created
  and managed by eksctl]
Resources:
  Role1:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRoleWithWebIdentity
          Condition:
            StringEquals:
              oidc.eks.us-east-1.amazonaws.com/id/A9B3BA8256D140CD72538AEF6F1EC2B5:aud: sts.amazonaws.com
              oidc.eks.us-east-1.amazonaws.com/id/A9B3BA8256D140CD72538AEF6F1EC2B5:sub: system:serviceaccount:kube-system:alb-ingress-controller
          Effect: Allow
          Principal:
            Federated: arn:aws:iam::642168441636:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/A9B3BA8256D140CD72538AEF6F1EC2B5
        Version: '2012-10-17'
      ManagedPolicyArns:
      - arn:aws:iam::642168441636:policy/ALBIngressControllerIAMPolicy
Outputs:
  Role1:
    Value:
      Fn::GetAtt: Role1.Arn